name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup QEMU
    - uses: docker/setup-qemu-action@v3.2.0
    
    - name: Docker Setup Buildx
    - uses: docker/setup-buildx-action@v3.6.1
    
    - name: Docker Login
    - uses: docker/login-action@v3.3.0
    - with:
        # Username used to log against the Docker registry
         username: ${{ secrets.DOCKER_PASSWORD }}
        # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.DOCKER_USERNAME }}
    - name: Build and push Docker images
    - uses: docker/build-push-action@v6.7.0
    - with:
       context: .
       push: true
          
